<?php
/* Copyright (C) 2013-2014  Stephan Kreutzer
 *
 * This file is part of automated_digital_publishing_server.
 *
 * automated_digital_publishing_server is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License version 3 or any later version,
 * as published by the Free Software Foundation.
 *
 * automated_digital_publishing_server is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License 3 for more details.
 *
 * You should have received a copy of the GNU Affero General Public License 3
 * along with automated_digital_publishing_server. If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * @file $/web/install/lang/en/install.lang.php
 * @author Stephan Kreutzer
 * @since 2013-09-14
 */



define("LANG_PAGETITLE", "Installation");

// -- Step 0 -------------------------------------------------------------------

define("LANG_STEP0_HEADER", "Installation");
define("LANG_STEP0_INTROTEXT", "“automated_digital_publishing_server” is a software package for running “automated_digital_publishing” on a server as an online service. As the latter is a native application to be run on a local computer, this server package is mainly based upon system calls and provides a web GUI on top of that. Therefore a hosting environment which allows the execution of native programs by system call from the webserver is required. “automated_digital_publishing_server” is <a href=\"http://en.wikipedia.org/wiki/Free_software\">free software</a> as <a href=\"http://www.gnu.org/philosophy/free-sw.html\">defined</a> by the <a href=\"http://www.fsf.org/\">Free Software Foundation</a> since it is licensed under the GNU Affero General Public License 3 or any later version of this license. The next step of the installation will show you the full text of the license, to which you agree by using the software. A short overview over the permissions you obtain: ".
                                 "<ul>".
                                 "  <li>You have permission to run the software. If you run the software in a way that users on a network can cause a usage of the software (for instance, if you run it as a service), you are required to establish a way by which users of that network can obtain a copy of the software you run (you are required to meet the conditions for distributing the software).</li>".
                                 "  <li>You have permission to distribute copies of the software, if you distribute the software under GNU AGPL 3 or any later version of the license.</li>".
                                 "  <li>You have permission to modify the software. You are required to license your modifications under GNU AGPL 3 or any later version of the license. You have permission to run and to distribute the modified software (you are required to meet the conditions for running and distributing the software then).".
                                 "</ul>".
                                 "But: ".
                                 "<ul>".
                                 "  <li>Values in the database are not required to be published with the source code, as long as they're generated by user interaction and not responsible for the inner workings of the software.</li>".
                                 "  <li>You are allowed to let the software link to other works without the requirement of releasing them under GNU AGPL 3 or any later version of the license, as long as such works aren't integrated into the software or the software depends on them for performing a function.</li>".
                                 "  <li>If you change values and settings in the software that are used for visual display only (which are not part of an algorithm, and if you don't change the way this values are accessed by the software), then you've just changed the configuration and haven't made a modification. In this specific case you're not required to release the changes under GNU AGPL 3 or any later version of the license, which allows you to create your own custom visual appearing of the software.</li>".
                                 "  <li>Free software allows both, commercial use and gratis use. Free software deals with the issue of freedom and digital rights, not price (freedom as in “free speech”, not as in “free beer” – gratis use is a possible side-effect).</li>".
                                 "</ul>".
                                 "Further notes and advice: ".
                                 "<ul>".
                                 "  <li>If you modify the software, you are required to mark out your changes very clearly.</li>".
                                 "  <li>If you modify the software, it would be nice of you to inform the main repository of the project (if such exists), the authors of the software (see AUTHORS file) about your actions. However, you are not required to do so.</li>".
                                 "  <li>This software was initially developed to promote collaboration. You might consider a similar direction for your actions as well instead of favouring protectionism. The license of this software was picked to hinder us from harming you and to hinder you from harming others (especially your users and licensees). The license effectively prevents you from denying others the digital rights that all computer users deserve by nature, both on the technical and on the legal level. You should not even try to find ways around the conditions of the license, since they're already benefiting you to the greatest extend possible. If you're uncomfortable with the license terms, you are free to not to use this software and to look for a more restrictively licensed “alternative”.</li>".
                                 "  <li>If you should spot a license violation (or an instance where it could be a license violation), please contact the authors of the software. Freedom can only be guarded when it is actively defended against its enemys. Don't worry, we do not intend to cause trouble to the person who violated the license, we would rather see the person complying with the license terms instead.</li>".
                                 "  <li>In case you experience any errors in the software or if you wish additional features, you might file an issue for it in the main repository (if such exists, currently <a href=\"https://github.com/skreutzer/automated_digital_publishing_server/issues\">this place</a> could be considered the main repository issue system) or by contacting the authors, if you either don't want or can't make the changes yourself. If you implement the changes yourself, it would be nice of you to send us a notification about the changes you've made.</li>".
                                 "</ul>".
                                 "Functional features of the software: ".
                                 "<ul>".
                                 "  <li>User management</li>".
                                 "  <li>Installation routine</li>".
                                 "  <li>Internationalization (support of multiple languages)</li>".
                                 "</ul>");
define("LANG_STEP0_PROCEEDTEXT", "Continue");

// -- Step 1 -------------------------------------------------------------------

define("LANG_STEP1_HEADER", "License Agreement");
define("LANG_STEP1_PROCEEDTEXT", "Agree");

// -- Step 2 -------------------------------------------------------------------

define("LANG_STEP2_HEADER", "System check");
define("LANG_STEP2_SAFEMODEON", "In the <tt>php.ini</tt> configuration file of the web server, <tt>safe_mode=Off</tt> isn't configured, so system calls can't be made. Warning: changing to <tt>safe_mode=Off</tt> could cause serious security threats, especially if other web applications are hosted on the same server as well!");
define("LANG_STEP2_JAVAVERSIONCHECK_PRE", "The installation tried to call the JavaVM by system call, the result was: ");
define("LANG_STEP2_JAVAVERSIONCHECK_POST", "If there are no details about the installed JavaVM shown above, there is either no JavaVM installed at all, or it is misconfigured. If the installation would be continued anyway, the result will be relatively unusable.");
define("LANG_STEP2_ADPMISSING", "“automated_digital_publishing” isn't installed. The executables of the software need to be copied into the <tt>\$/automated_digital_publishing/</tt> directory, without overwriting or deleting the files of “automated_digital_publishing_server”, which are already there. Additionally, some directories there might need write permission.");
define("LANG_STEP2_ADPNOSETUP", "“automated_digital_publishing” isn't configured. <tt>\$/automated_digital_publishing/workflows/setup1</tt> needs to be executed. Check reading permissions for the files created by <tt>setup1</tt>.");
define("LANG_STEP2_CONTINUE", "Continue");
define("LANG_STEP2_RETRY", "Retry");

// -- Step 3 -------------------------------------------------------------------

define("LANG_STEP3_HEADER", "Database Settings");
define("LANG_STEP3_REQUIREMENTS", "This software requires a running MySQL database server. Please fill in the database connection settings. They'll get written into the file <tt>\$/libraries/database_connect.inc.php</tt> of the software installation directory.");
define("LANG_STEP3_HOSTDESCRIPTION", "Address of the database server");
define("LANG_STEP3_USERNAMEDESCRIPTION", "Database username");
define("LANG_STEP3_PASSWORDDESCRIPTION", "Password of that database user");
define("LANG_STEP3_DATABASENAMEDESCRIPTION", "Name of the database which will hold the tables");
define("LANG_STEP3_TABLEPREFIXDESCRIPTION", "Prefix for table names (could be empty if no name collusions are expected – prefix ends usually with an underscore '_')");
define("LANG_STEP3_SAVETEXT", "Save settings");
define("LANG_STEP3_EDITTEXT", "Edit settings");
define("LANG_STEP3_PROCEEDTEXT", "Confirm settings");
define("LANG_STEP3_DBCONNECTSUCCEEDED", "Connection to the database was successfully established!");
// Corresponding with LANG_STEP4_DBCONNECTFAILED.
define("LANG_STEP3_DBCONNECTFAILED", "Connection to the database couldn't be established. Error description: ");
// Corresponding with LANG_STEP4_DBCONNECTFAILEDNOERRORINFO.
define("LANG_STEP3_DBCONNECTFAILEDNOERRORINFO", "No error details!");
define("LANG_STEP3_DATABASECONNECTFILECREATEFAILED", "The attempt to create <tt>\$/libraries/database_connect.inc.php</tt> failed!");
define("LANG_STEP3_DATABASECONNECTFILEISWRITABLE", "<tt>\$/libraries/database_connect.inc.php</tt> is writable!");
define("LANG_STEP3_DATABASECONNECTFILEISNTWRITABLE", "<tt>\$/libraries/database_connect.inc.php</tt> isn't writable! Either there are no write permissions granted for the directory <tt>\$/libraries/</tt>, so that the file can't be created, or the file <tt>\$/libraries/database_connect.inc.php</tt> does already exist, but permission for writing the file isn't sufficient. You might have to enable write permission manually on the server for the directory <tt>\$/libraries/</tt> and/or for the file <tt>\$/libraries/database_connect.inc.php</tt> (if already existing) with a FTP program (CHMOD command) or via remote connection. Don't forget to reset the permissions after the installation is completed.");
define("LANG_STEP3_DATABASECONNECTFILEWRITABLEOPENFAILED", "<tt>\$/libraries/database_connect.inc.php</tt> looked to be writable, but opening the file failed!");
define("LANG_STEP3_DATABASECONNECTFILEWRITEFAILED", "<tt>\$/libraries/database_connect.inc.php</tt> looked to be writable, was successfully opened, but can't be actually written!");
define("LANG_STEP3_DATABASECONNECTFILEWRITESUCCEEDED", "Writing <tt>\$/libraries/database_connect.inc.php</tt> succeeded!");
define("LANG_STEP3_DATABASECONNECTFILEISNTREADABLE", "<tt>\$/libraries/database_connect.inc.php</tt> isn't readable! Either there are no read permissions granted for the directory <tt>\$/libraries/</tt>, so that the file can't be accessed, or the file <tt>\$/libraries/database_connect.inc.php</tt> itself lacks read permission. You might have to enable read permission manually on the server for the directory <tt>\$/libraries/</tt> and/or for the file <tt>\$/libraries/database_connect.inc.php</tt> with a FTP program (CHMOD command) or another file transfer program. Don't forget to reset the permissions after the installation is completed.");
define("LANG_STEP3_DATABASECONNECTFILEISREADABLE", "Written <tt>\$/libraries/database_connect.inc.php</tt> is readable!");
define("LANG_STEP3_DATABASECONNECTFILEDOESNTEXIST", "<tt>\$/libraries/database_connect.inc.php</tt> doesn't exist!");

// -- Step 4 -------------------------------------------------------------------

define("LANG_STEP4_HEADER", "Initialization");
define("LANG_STEP4_INITIALIZETEXT", "Initialize");
define("LANG_STEP4_INITIALIZATIONDESCRIPTION", "The software is about to be initialized. This includes the creation of the tables in the database.");
define("LANG_STEP4_CHECKBOXDESCRIPTIONDROPEXISTINGTABLES", "Delete tables that already exist (warning: tables can't be recovered!)");
define("LANG_STEP4_CHECKBOXDESCRIPTIONKEEPEXISTINGTABLES", "Only create tables, if not already existing (will keep existing tables without change)");
// Corresponding with LANG_STEP3_DBCONNECTFAILED.
define("LANG_STEP4_DBCONNECTFAILED", "Connection to the database couldn't be established. Error description: ");
// Corresponding with LANG_STEP3_DBCONNECTFAILEDNOERRORINFO.
define("LANG_STEP4_DBCONNECTFAILEDNOERRORINFO", "No error details!");
define("LANG_STEP4_DBOPERATIONFAILED", "Database operation failed. Error description: ");
define("LANG_STEP4_DBOPERATIONFAILEDNOERRORINFO", "No error details!");
define("LANG_STEP4_DBCOMMITFAILED", "Committing the database operations failed!");
define("LANG_STEP4_DBOPERATIONSUCCEEDED", "Initialization was successful!");
define("LANG_STEP4_COMPLETETEXT", "Complete");

// -- Step 5 -------------------------------------------------------------------

define("LANG_STEP5_HEADER", "Complete!");
define("LANG_STEP5_COMPLETETEXT", "Installation succeeded! The installation routine will try to delete itself. If it can't succeed (login on the main page won't be possible then, instead, you'll get forwarded to the installation again), you have to delete the directory <tt>\$/install/</tt> manually, or at least the file <tt>\$/install/install.php</tt>. Then the login form should be accessible.");
define("LANG_STEP5_EXITTEXT", "Exit");



?>
